"""Streaming domain rules for restoring anonymized placeholders."""
from __future__ import annotations

import re
from typing import Mapping

from domain.deanonymization import DeanonymizationMap


PARTIAL_PLACEHOLDER_PATTERN = re.compile(r"\[[A-Z]*(?:_\d*)?$")


class StreamingDeanonymizer:
    """Restore placeholders while assistant text is received in chunks."""

    def __init__(
        self,
        replacements: Mapping[str, str],
        strict: bool = True,
    ) -> None:
        """Initialize the streaming deanonymizer.

        Args:
            replacements (Mapping[str, str]): The placeholder-to-original-value
                mapping generated during anonymization.
            strict (bool): Whether complete unknown placeholders should fail.
        """
        self._deanonymization_map = DeanonymizationMap(replacements)
        self._strict = strict
        self._buffer = ""

    def push(self, chunk: str) -> str:
        """Process a response chunk and return safe restored text.

        Args:
            chunk (str): The next text chunk generated by the assistant.

        Returns:
            str: The restored text that is safe to stream to the user.

        Raises:
            ValueError: If strict mode finds a complete unknown placeholder.
        """
        if not chunk:
            return ""

        self._buffer += chunk
        safe_text, self._buffer = self._split_safe_text(self._buffer)
        self._ensure_known_placeholders(safe_text)
        restored_text, _ = self._deanonymization_map.restore(safe_text)
        return restored_text

    def flush(self) -> str:
        """Restore and return any text still retained in the buffer.

        Returns:
            str: The restored remaining text.

        Raises:
            ValueError: If strict mode finds a complete unknown placeholder.
        """
        remaining_text = self._buffer
        self._buffer = ""
        self._ensure_known_placeholders(remaining_text)
        restored_text, _ = self._deanonymization_map.restore(remaining_text)
        return restored_text

    def _split_safe_text(self, text: str) -> tuple[str, str]:
        """Split stream text into safe text and retained partial placeholder.

        Args:
            text (str): The buffered stream text.

        Returns:
            tuple[str, str]: The text that can be emitted and the suffix that
            must be retained because it may be an incomplete placeholder.
        """
        last_open_bracket = text.rfind("[")
        if last_open_bracket == -1:
            return text, ""

        suffix = text[last_open_bracket:]
        if "]" in suffix:
            return text, ""

        if PARTIAL_PLACEHOLDER_PATTERN.fullmatch(suffix):
            return text[:last_open_bracket], suffix

        return text, ""

    def _ensure_known_placeholders(self, text: str) -> None:
        """Validate complete placeholders when strict mode is enabled.

        Args:
            text (str): The text to validate.

        Raises:
            ValueError: If strict mode finds a complete unknown placeholder.
        """
        if not self._strict:
            return

        unknown_placeholders = self._deanonymization_map.find_unknown_placeholders(
            text
        )
        if unknown_placeholders:
            placeholders = ", ".join(unknown_placeholders)
            raise ValueError(
                f"Unknown placeholders cannot be restored: {placeholders}"
            )
